name: ML Pipeline CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

#      - name: Установка зависимостей
#        run: pip install -r requirements.txt

      - name: Установка зависимостей
        run: |
          # Сначала устанавливаем requirements.txt с игнорированием конфликтов
          pip install -r requirements.txt --no-deps || true
          # Потом устанавливаем все зависимости (pip сам разрешит что можно)
          pip install -r requirements.txt
          # И только в конце явно устанавливаем DVC (чтобы он точно был)
          pip install dvc dvc-s3

      - name: Загрузка данных через DVC (из Cloud.ru)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: dvc pull

      - name: Запуск тестов
        run: pytest tests/